const marquesBeaute = [
    "L'Oréal",
    "Maybelline",
    "MAC Cosmetics",
    "NARS",
    "Estée Lauder",
    "Chanel",
    "Dior",
    "Urban Decay",
    "Too Faced",
    "Benefit",
    "Clinique",
    "Guerlain",
    "Yves Saint Laurent",
    "Bobbi Brown",
    "Anastasia Beverly Hills",
    "Huda Beauty",
    "Fenty Beauty",
    "Kylie Cosmetics",
    "Tarte Cosmetics",
    "Laura Mercier"
  ];